### ISSUE TITLE
An upstream wpa_supplicant update broke WPA2/3 on all Broadcom chips

### ISSUE THREAD

**Issue by danilaros** [ublue-os/bluefin#1623]
### Describe the bug

An upstream wpa_supplicant update broke WPA2/3 on all Broadcom chips. This is been already fixed in Fedora but in the latest stable image of Bluefin the bug is still present. 

Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=2302577

### What did you expect to happen?

Please include the Fedora Fix in the Bluefin Image.

Tks.

**Comment by danilaros** [comment]
I noted that is already a bug report open here:

https://github.com/ublue-os/bluefin/issues/1591

**Comment by castrojo** [comment]
Can someone confirm that it's fixed in the :latest branch? If so we can fire off stable/gts builds.

**Comment by danilaros** [comment]
> Can someone confirm that it's fixed in the :latest branch? If so we can fire off stable/gts builds.

Hi. I rebase my system from the stable branch to the latest branch and the issue is still present.

**Comment by castrojo** [comment]
Ok try it now!

**Comment by danilaros** [comment]
> Ok try it now!

Hi again. I run today a "ujust update" in latest branch and reboot. 
Unfortunately the problem is not solved yet, the wifi card is detected but doesn't detect wpa2/3 networks.

**Comment by danilaros** [comment]
I realized that today and in 24/08 another 2 new bugs were opened in Red Hat Bugzilla because of this problem, probably we have to wait them to be fixed upstream? 
https://bugzilla.redhat.com/show_bug.cgi?id=2308098
https://bugzilla.redhat.com/show_bug.cgi?id=2307718

**Comment by KyberNull** [comment]
Can't we ship wpa_supplicant v2.10 in bluefin until the bug is fixed upstream

**Comment by castrojo** [comment]
Can someone confirm the version to hold back and that it works?

**Comment by danilaros** [comment]
> Can someone confirm the version to hold back and that it works?

Hi. I run a ujust update today in the Latest Branch and is all working fine now :)
